version: '2'

services:
  app:
    build: ./
    image: peanut-app:latest
    ports:
      - "8000:80"
    networks:
      - valu-incentive-search
    restart: always

  queue-worker:
    image: peanut-app:latest
    entrypoint: ""
    command: "php artisan queue:work --delay=3600 --tries=2 --timeout=30"
    depends_on:
      - app
    networks:
      - valu-incentive-search
    restart: always

networks:
  valu-incentive-search:
    driver: bridge
